## interRAI recoding

answers_wide$`Living arrangement prior to admission`[answers_wide$`Living arrangement prior to admission` == "Alone"] <- "0 (Alone)"
answers_wide$`Living arrangement prior to admission`[answers_wide$`Living arrangement prior to admission` != "Alone"] <- "1 (Not Alone)"
answers_wide$`Time since last hospital stay - code for most recent instance in LAST 90 DAYS`[1:4] <- "1 or 2 or 3 or 4 (Hospitalisation within 90 days)"
answers_wide$`Time since last hospital stay - code for most recent instance in LAST 90 DAYS`[5] <- "5 (Now in hospital)"
answers_wide$`Time since last hospital stay - code for most recent instance in LAST 90 DAYS`[9] <- "0 (No hospitalisation within 90 days)"
answers_wide$Hearing[9] <- "0 (Adequate)"
answers_wide$Hearing[1] <- "1 (Impaired)"
answers_wide$Hearing[2:4] <- "2 or 3 or 4 (Moderately to severely impaired)"
answers_wide$`Hearing aid used`[1] <- "1 (Yes)"
answers_wide$`Hearing aid used`[9] <- "0 (No)"
answers_wide$`Vision in adequate light`[9] <- "0 (Adequate)"
answers_wide$`Vision in adequate light`[1] <- "1 (Impaired)"
answers_wide$`Vision in adequate light`[2:4] <- "2 or 3 or 4 (Moderately to severely impaired)"
answers_wide$`Visual aid used`[1] <- "1 (Yes)"
answers_wide$`Visual aid used`[9] <- "0 (No)"
answers_wide$`Social relationships - Says or indicates that he / she feels lonely`[1] <- "1 (Yes)"
answers_wide$`Social relationships - Says or indicates that he / she feels lonely`[9] <- "0 (No)"
answers_wide$`Length of time alone during the day`[1] <- "1 (1-2 hours)"
answers_wide$`Length of time alone during the day`[2] <- "2 (More than 2 hours but less than 8 hours)"
answers_wide$`Length of time alone during the day`[3] <- "3 (8 hours or more)"
answers_wide$`Length of time alone during the day`[9] <- "0 (Less than 1 hour)"
answers_wide$`Strengths - Strong and supportive relationship with family`[1] <- "1 (Yes)"
answers_wide$`Strengths - Strong and supportive relationship with family`[9] <- "0 (No)"
answers_wide$`Hours exercise`[1:2] <- "1 or 2 (Less than 2 hours)"
answers_wide$`Hours exercise`[3:4] <- "3 or 4 (More than 3 hours)"
answers_wide$`Hours exercise`[9] <- "0 (None)"
answers_wide$`Days went out`[1] <- "1 (Did not go out in last 3 days; but usually goes out over a 3-day period)"
answers_wide$`Days went out`[2:3] <- "2 or 3 (1 or more days)"
answers_wide$`Days went out`[9] <- "0 (No days out)"
answers_wide$`Bladder continence`[1:5] <- "1 or 2 or 3 or 4 or 5 or 8 (Incontinent)"
answers_wide$`Bladder continence`[8] <- "1 or 2 or 3 or 4 or 5 or 8 (Incontinent)"
answers_wide$`Bladder continence`[9] <- "0 (Continent)"
answers_wide$`Bowel continence`[1:5] <- "1 or 2 or 3 or 4 or 5 or 8 (Incontinent)"
answers_wide$`Bowel continence`[8] <- "1 or 2 or 3 or 4 or 5 or 8 (Incontinent)"
answers_wide$`Bowel continence`[9] <- "0 (Continent)"
answers_wide$`Disease diagnosis - Alzheimer's disease`[1:3] <- "1 or 2 or 3 (Present)"
answers_wide$`Disease diagnosis - Alzheimer's disease`[9] <- "0 (Not present)"
answers_wide$`Disease diagnosis - Dementia other than Alzheimer's disease`[1:3] <- "1 or 2 or 3 (Present)"
answers_wide$`Disease diagnosis - Dementia other than Alzheimer's disease`[9] <- "0 (Not present)"
answers_wide$Falls[1:3] <- "1 (≥1 Falls in last 90 days)"
answers_wide$Falls[9] <- "0 (No falls in last 90 days)"
answers_wide$`Recent Falls`[1] <- "1 (Yes)"
answers_wide$`Recent Falls`[9] <- "0 (No)"
answers_wide$`Problem frequency - Unsteady gait`[1:4] <- "1 or 2 or 3 or 4 (Present)"
answers_wide$`Problem frequency - Unsteady gait`[9] <- "0 (No)"
answers_wide$`Problem frequency - Chest pain`[1:4] <- "1 or 2 or 3 or 4 (Present)"
answers_wide$`Problem frequency - Chest pain`[9] <- "0 (No)"
answers_wide$`Problem frequency - Delusions (0-4)`[1:4] <- "1 or 2 or 3 or 4 (Present)"
answers_wide$`Problem frequency - Delusions (0-4)`[9] <- "0 (No)"
answers_wide$`Problem frequency - Hallucinations (0-4)`[1:4] <- "1 or 2 or 3 or 4 (Present)"
answers_wide$`Problem frequency - Hallucinations (0-4)`[9] <- "0 (No)"
answers_wide$`Smokes tobacco daily`[1:2] <- "1 or 2 (Yes)"
answers_wide$`Smokes tobacco daily`[9] <- "0 (No)"
answers_wide$`Alcohol- Highest number of drinks in any “single sitting” in LAST 14 DAYS`[2:3] <- "2 or 3 (More than 1)"
answers_wide$`Alcohol- Highest number of drinks in any “single sitting” in LAST 14 DAYS`[1] <- "1 (1)"
answers_wide$`Alcohol- Highest number of drinks in any “single sitting” in LAST 14 DAYS`[9] <- "0 (None)"
answers_wide$`Informal helper(s) is unable to continue in caring activities`[1] <- "1 (Yes)"
answers_wide$`Informal helper(s) is unable to continue in caring activities`[9] <- "0 (No)"
answers_wide$`Primary informal helper expresses feelings of distress, anger, or depression`[1] <- "1 (Yes)"
answers_wide$`Primary informal helper expresses feelings of distress, anger, or depression`[9] <- "0 (No)"
answers_wide$`Scale - ADL Hierarchy`[1:2] <- "1 or 2 (Mildly dependent)"
answers_wide$`Scale - ADL Hierarchy`[3:6] <- "3 or 4 or 5 or 6 (Moderately to severely dependent)"
answers_wide$`Scale - ADL Hierarchy`[9] <- "0 (Independent)"
answers_wide$`Scale - CHESS`[1] <- "0 or 1 (Stable)"
answers_wide$`Scale - CHESS`[9] <- "0 or 1 (Stable)"
answers_wide$`Scale - CHESS`[2:5] <- "2 or 3 or 4 or 5 (Unstable)"
#answers_wide$`Scale - CHESS`[4:5] <- "4-5 (Highly unstable)"
answers_wide$`Scale - CPS`[1:9] <- "0 or 1 (Intact or borderline intact)"
answers_wide$`Scale - CPS`[2:3] <- "2 or 3 (Mild to moderate impairment)"
answers_wide$`Scale - CPS`[4:6] <- "4 or 5 or 6 (Moderately severe to very severe impairment)"
answers_wide$`Scale - CPS`[7:8] <- NA
answers_wide$`Scale - DRS`[1:2] <- "0 or 1 or 2 (No-minimal)"
answers_wide$`Scale - DRS`[3:5] <- "3 or 4 or 5 (Moderate)"
answers_wide$`Scale - DRS`[6:8] <- "6 or 7 or 8 or 9 or 10 or 11 or 12 or 13 or 14 (Severe)"
answers_wide$`Scale - DRS`[10:15] <- "6 or 7 or 8 or 9 or 10 or 11 or 12 or 13 or 14 (Severe)"
answers_wide$`Scale - DRS`[9] <- "0 or 1 or 2 (No-minimal)"
answers_wide$`Scale - MAPLE`[2:3] <- "2 or 3 (Mild to moderate priority; range of home care services)"
answers_wide$`Scale - MAPLE`[4:5] <- "4 or 5 (High to very high priority; hospital care or community support)"
answers_wide$`Scale - Pain`[9] <- "0 (No pain)"
answers_wide$`Scale - Pain`[1:2] <- "1 or 2 (Less than severe)"
answers_wide$`Scale - Pain`[3:4] <- "3 or 4 (Severe-excruciating)"
answers_wide$`Scale - Aggressive Behaviour`[9] <- "0 (No instances of aggressive behaviour)"
answers_wide$`Scale - Aggressive Behaviour`[1:4] <- "1 or 2 or 3 or 4 (Mildly aggressive behaviour)"
answers_wide$`Scale - Aggressive Behaviour`[5:8] <- "5 or 6 or 7 or 8 or 9 or 10 or 11 or 12 (Moderate to severely aggressive behaviour)"
answers_wide$`Scale - Aggressive Behaviour`[10:13] <- "5 or 6 or 7 or 8 or 9 or 10 or 11 or 12 (Moderate to severely aggressive behaviour)"
answers_wide$`Falls - In last 30 days`[1:2] <- "1 (Yes)"
answers_wide$`Falls - In last 30 days`[9] <- "0 (No)"
answers_wide$`Falls - 31-90 days ago`[1:2] <- "1 (Yes)"
answers_wide$`Falls - 31-90 days ago`[9] <- "0 (No)"
answers_wide$`Falls - 91-180 days ago`[1:2] <- "1 (Yes)"
answers_wide$`Falls - 91-180 days ago`[9] <- "0 (No)"
answers_wide$`Self-rated health`[9] <- "0-1 Excellent or Good"
answers_wide$`Self-rated health`[1] <- "0-1 Excellent or Good"
answers_wide$`Self-rated health`[2] <- "2 Fair"
answers_wide$`Self-rated health`[3] <- "3 Poor"
answers_wide$`Self-rated health`[8] <- "8 Could not (would not) respond"